// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNP_gtUswTCVXHKm2L2BZSFxQpYlungg',
    appId: '1:147506603318:web:7ef6560d8bce2044717f97',
    messagingSenderId: '147506603318',
    projectId: 'englishlearning-ba848',
    authDomain: 'englishlearning-ba848.firebaseapp.com',
    storageBucket: 'englishlearning-ba848.firebasestorage.app',
    measurementId: 'G-6ZR815ZBPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEJHnq44mPpbJ62WwUo_R3Vat9SUITAk',
    appId: '1:147506603318:android:87ce7aa8bd20f586717f97',
    messagingSenderId: '147506603318',
    projectId: 'englishlearning-ba848',
    storageBucket: 'englishlearning-ba848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPjbHTLNSjdJuyfOkezg4cF-Yvr8d_f0',
    appId: '1:147506603318:ios:2d511d2fc1b9cbd9717f97',
    messagingSenderId: '147506603318',
    projectId: 'englishlearning-ba848',
    storageBucket: 'englishlearning-ba848.firebasestorage.app',
    iosBundleId: 'com.example.englishLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPjbHTLNSjdJuyfOkezg4cF-Yvr8d_f0',
    appId: '1:147506603318:ios:2d511d2fc1b9cbd9717f97',
    messagingSenderId: '147506603318',
    projectId: 'englishlearning-ba848',
    storageBucket: 'englishlearning-ba848.firebasestorage.app',
    iosBundleId: 'com.example.englishLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNP_gtUswTCVXHKm2L2BZSFxQpYlungg',
    appId: '1:147506603318:web:47330fe8ca267312717f97',
    messagingSenderId: '147506603318',
    projectId: 'englishlearning-ba848',
    authDomain: 'englishlearning-ba848.firebaseapp.com',
    storageBucket: 'englishlearning-ba848.firebasestorage.app',
    measurementId: 'G-K6HBNB11VH',
  );
}
